name: Deploy to InfinityFree

# Run manually or on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - web_version

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Upload code via FTP
      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_40163549
          password: TW1ZFenyNTlSFP
          server-dir: /geoguesser.gamer.gd/htdocs/  # For addon domains
          timeout: 86400000
          log-level: standard
